sudo: false
os:
  - linux
  - osx
language: go
env:
  - secure: "iEmROaMU0nPbs+gBLAL5a+SXQZTi7ynUiZs4rjFyg2eugIBupdEKrH8G06UcsU9QteO8kVuHcgJo2ZwU4BhS2GkBZj8VsoY+N51GKBEptBHbOXJeg/HlTFxJ6Tm9ilmx5M6N4z5acNO/9znSkjXAN6OGxMkCD9Ohxph0UMTMhuk="
go:
  - 1.3
  - 1.4
  - 1.5
  - tip
install:
  - go get ./...
  - go get -u github.com/remyoudompheng/go-misc/deadcode
  - go get -u github.com/fzipp/gocyclo
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - gofmt -s -d *.go
  - go vet
  - deadcode
  - gocyclo -over 10 *.go
  - go test -race -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
